version: '3.4'

x-env: &env
  environment:
    FIN_LOCATION: /fin
    STREAMLIT_FIN_SERVER_PORT: 8501

volumes:
  production_traefik: {}

services:
  streamlit-fin:
    <<: *env
    build: 
      context: .
      dockerfile: ./compose/streamlit-fin/Dockerfile
    image: streamlit_fin_production
    container_name: streamlit_fin_app
    restart: always
    expose:
      - ${STREAMLIT_FIN_SERVER_PORT}
    command: streamlit run --server.port=$STREAMLIT_FIN_SERVER_PORT --server.address=0.0.0.0 --server.baseUrlPath=$FIN_LOCATION src/app.py

  traefik:
    <<: *env
    build:
      context: .
      dockerfile: ./compose/traefik/Dockerfile
    image: traefik_production
    volumes:
      - production_traefik:/etc/traefik/acme:z
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"