log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure
          scheme: https

  web-secure:
    # https
    address: ":443"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "furyx@hotmail.com"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: "Host(`furyhawk.lol`, `www.furyhawk.lol`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: streamlit_app
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt
    blog-router:
      rule: "Host(`blog.furyhawk.lol`)"
      entryPoints:
        - web-secure
      # redirect to external blog
      middlewares:
        - redirect
      service: dummy
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

    redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectregex:
        regex: "^https://blog.furyhawk.lol/(.*)"
        replacement: "https://furyhawk.github.io/124c41/${1}"
        permanent: true

  services:
    streamlit_app:
      loadBalancer:
        servers:
          - url: http://streamlit_app:8501

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
